# Generated by Django 3.0.3 on 2020-02-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200203_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(default='game title', max_length=40),
            preserve_default=False,
        ),
    ]
