# Generated by Django 3.0.3 on 2020-02-20 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='slug',
        ),
    ]
