# Generated by Django 3.0.3 on 2020-02-11 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Gamely', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='player_pics')),
                ('favoriteGame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gamely.Game')),
                ('favoritePlatform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gamely.Platform')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
