# Generated by Django 3.0.3 on 2020-02-21 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_game_image'),
        ('players', '0002_auto_20200219_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='favorite_game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Game'),
        ),
    ]
